package br.edu.imepac.comum.config;

import br.edu.imepac.comum.dtos.perfil.PerfilDto;
import br.edu.imepac.comum.dtos.perfil.PerfilRequest;
import br.edu.imepac.comum.models.Perfil;
import org.modelmapper.ModelMapper;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class ConfigModelMapper {

    @Bean
    public ModelMapper modelMapper() {
        ModelMapper modelMapper = new ModelMapper();
        modelMapper.typeMap(PerfilRequest.class, Perfil.class).addMappings(mapper -> {
            mapper.map(PerfilRequest::isCadastrarFuncionario, Perfil::setCadastrarFuncionario);
            mapper.map(PerfilRequest::isLerFuncionario,Perfil::setLerFuncionario);
            mapper.map(PerfilRequest::isAtualizarFuncionario,Perfil::setAtualizarFuncionario);
            mapper.map(PerfilRequest::isDeletarFuncionario,Perfil::setDeletarFuncionario);
            mapper.map(PerfilRequest::isListarFuncionario,Perfil::setListarFuncionario);
            mapper.map(PerfilRequest::isCadastrarPaciente,Perfil::setCadastrarPaciente);
            mapper.map(PerfilRequest::isLerPaciente,Perfil::setLerPaciente);
            mapper.map(PerfilRequest::isAtualizarPaciente,Perfil::setAtualizarPaciente);
            mapper.map(PerfilRequest::isDeletarPaciente,Perfil::setDeletarPaciente);
            mapper.map(PerfilRequest::isListarPaciente,Perfil::setListarPaciente);
            mapper.map(PerfilRequest::isCadastrarConsulta,Perfil::setCadastrarConsulta);
            mapper.map(PerfilRequest::isLerConsulta,Perfil::setLerConsulta);
            mapper.map(PerfilRequest::isAtualizarConsulta,Perfil::setAtualizarConsulta);
            mapper.map(PerfilRequest::isDeletarConsulta,Perfil::setDeletarConsulta);
            mapper.map(PerfilRequest::isListarConsulta,Perfil::setListarConsulta);
            mapper.map(PerfilRequest::isCadastrarEspecialidade,Perfil::setCadastrarEspecialidade);
            mapper.map(PerfilRequest::isLerEspecialidade,Perfil::setLerEspecialidade);
            mapper.map(PerfilRequest::isAtualizarEspecialidade,Perfil::setAtualizarEspecialidade);
            mapper.map(PerfilRequest::isDeletarEspecialidade,Perfil::setDeletarEspecialidade);
            mapper.map(PerfilRequest::isListarEspecialidade,Perfil::setListarEspecialidade);
            mapper.map(PerfilRequest::isCadastrarEspecialidade,Perfil::setCadastrarEspecialidade);
            mapper.map(PerfilRequest::isLerEspecialidade,Perfil::setLerEspecialidade);
            mapper.map(PerfilRequest::isAtualizarEspecialidade,Perfil::setAtualizarEspecialidade);
            mapper.map(PerfilRequest::isDeletarEspecialidade,Perfil::setDeletarEspecialidade);
            mapper.map(PerfilRequest::isListarEspecialidade,Perfil::setListarEspecialidade);
            mapper.map(PerfilRequest::isCadastrarConvenio,Perfil::setCadastrarConvenio);
            mapper.map(PerfilRequest::isLerConvenio,Perfil::setLerConvenio);
            mapper.map(PerfilRequest::isAtualizarConvenio,Perfil::setAtualizarConvenio);
            mapper.map(PerfilRequest::isDeletarConvenio,Perfil::setDeletarConvenio);
            mapper.map(PerfilRequest::isListarConvenio,Perfil::setListarConvenio);
            mapper.map(PerfilRequest::isCadastrarProntuario,Perfil::setCadastrarProntuario);
            mapper.map(PerfilRequest::isLerProntuario,Perfil::setLerProntuario);
            mapper.map(PerfilRequest::isAtualizarProntuario,Perfil::setAtualizarProntuario);
            mapper.map(PerfilRequest::isDeletarProntuario,Perfil::setDeletarProntuario);
            mapper.map(PerfilRequest::isListarProntuario,Perfil::setListarProntuario);
            mapper.map(PerfilRequest::isCadastrarPerfil,Perfil::setCadastrarPerfil);
            mapper.map(PerfilRequest::isLerPerfil,Perfil::setLerPerfil);
            mapper.map(PerfilRequest::isAtualizarPerfil,Perfil::setAtualizarPerfil);
            mapper.map(PerfilRequest::isDeletarPerfil,Perfil::setDeletarPerfil);
            mapper.map(PerfilRequest::isListarPerfil,Perfil::setListarPerfil);
        });
        modelMapper.typeMap(Perfil.class,PerfilRequest.class).addMappings(mapper -> {
            mapper.map(Perfil::isCadastrarFuncionario, PerfilRequest::setCadastrarFuncionario);
            mapper.map(Perfil::isLerFuncionario,PerfilRequest::setLerFuncionario);
            mapper.map(Perfil::isAtualizarFuncionario,PerfilRequest::setAtualizarFuncionario);
            mapper.map(Perfil::isDeletarFuncionario,PerfilRequest::setDeletarFuncionario);
            mapper.map(Perfil::isListarFuncionario,PerfilRequest::setListarFuncionario);
            mapper.map(Perfil::isCadastrarPaciente,PerfilRequest::setCadastrarPaciente);
            mapper.map(Perfil::isLerPaciente,PerfilRequest::setLerPaciente);
            mapper.map(Perfil::isAtualizarPaciente,PerfilRequest::setAtualizarPaciente);
            mapper.map(Perfil::isDeletarPaciente,PerfilRequest::setDeletarPaciente);
            mapper.map(Perfil::isListarPaciente,PerfilRequest::setListarPaciente);
            mapper.map(Perfil::isCadastrarConsulta,PerfilRequest::setCadastrarConsulta);
            mapper.map(Perfil::isLerConsulta,PerfilRequest::setLerConsulta);
            mapper.map(Perfil::isAtualizarConsulta,PerfilRequest::setAtualizarConsulta);
            mapper.map(Perfil::isDeletarConsulta,PerfilRequest::setDeletarConsulta);
            mapper.map(Perfil::isListarConsulta,PerfilRequest::setListarConsulta);
            mapper.map(Perfil::isCadastrarEspecialidade,PerfilRequest::setCadastrarEspecialidade);
            mapper.map(Perfil::isLerEspecialidade,PerfilRequest::setLerEspecialidade);
            mapper.map(Perfil::isAtualizarEspecialidade,PerfilRequest::setAtualizarEspecialidade);
            mapper.map(Perfil::isDeletarEspecialidade,PerfilRequest::setDeletarEspecialidade);
            mapper.map(Perfil::isListarEspecialidade,PerfilRequest::setListarEspecialidade);
            mapper.map(Perfil::isCadastrarEspecialidade,PerfilRequest::setCadastrarEspecialidade);
            mapper.map(Perfil::isLerEspecialidade,PerfilRequest::setLerEspecialidade);
            mapper.map(Perfil::isAtualizarEspecialidade,PerfilRequest::setAtualizarEspecialidade);
            mapper.map(Perfil::isDeletarEspecialidade,PerfilRequest::setDeletarEspecialidade);
            mapper.map(Perfil::isListarEspecialidade,PerfilRequest::setListarEspecialidade);
            mapper.map(Perfil::isCadastrarConvenio,PerfilRequest::setCadastrarConvenio);
            mapper.map(Perfil::isLerConvenio,PerfilRequest::setLerConvenio);
            mapper.map(Perfil::isAtualizarConvenio,PerfilRequest::setAtualizarConvenio);
            mapper.map(Perfil::isDeletarConvenio,PerfilRequest::setDeletarConvenio);
            mapper.map(Perfil::isListarConvenio,PerfilRequest::setListarConvenio);
            mapper.map(Perfil::isCadastrarProntuario,PerfilRequest::setCadastrarProntuario);
            mapper.map(Perfil::isLerProntuario,PerfilRequest::setLerProntuario);
            mapper.map(Perfil::isAtualizarProntuario,PerfilRequest::setAtualizarProntuario);
            mapper.map(Perfil::isDeletarProntuario,PerfilRequest::setDeletarProntuario);
            mapper.map(Perfil::isListarProntuario,PerfilRequest::setListarProntuario);
            mapper.map(Perfil::isCadastrarPerfil,PerfilRequest::setCadastrarPerfil);
            mapper.map(Perfil::isLerPerfil,PerfilRequest::setLerPerfil);
            mapper.map(Perfil::isAtualizarPerfil,PerfilRequest::setAtualizarPerfil);
            mapper.map(Perfil::isDeletarPerfil,PerfilRequest::setDeletarPerfil);
            mapper.map(Perfil::isListarPerfil,PerfilRequest::setListarPerfil);
        });
        modelMapper.typeMap(PerfilDto.class, Perfil.class).addMappings(mapper -> {
            mapper.map(PerfilDto::isCadastrarFuncionario, Perfil::setCadastrarFuncionario);
            mapper.map(PerfilDto::isLerFuncionario,Perfil::setLerFuncionario);
            mapper.map(PerfilDto::isAtualizarFuncionario,Perfil::setAtualizarFuncionario);
            mapper.map(PerfilDto::isDeletarFuncionario,Perfil::setDeletarFuncionario);
            mapper.map(PerfilDto::isListarFuncionario,Perfil::setListarFuncionario);
            mapper.map(PerfilDto::isCadastrarPaciente,Perfil::setCadastrarPaciente);
            mapper.map(PerfilDto::isLerPaciente,Perfil::setLerPaciente);
            mapper.map(PerfilDto::isAtualizarPaciente,Perfil::setAtualizarPaciente);
            mapper.map(PerfilDto::isDeletarPaciente,Perfil::setDeletarPaciente);
            mapper.map(PerfilDto::isListarPaciente,Perfil::setListarPaciente);
            mapper.map(PerfilDto::isCadastrarConsulta,Perfil::setCadastrarConsulta);
            mapper.map(PerfilDto::isLerConsulta,Perfil::setLerConsulta);
            mapper.map(PerfilDto::isAtualizarConsulta,Perfil::setAtualizarConsulta);
            mapper.map(PerfilDto::isDeletarConsulta,Perfil::setDeletarConsulta);
            mapper.map(PerfilDto::isListarConsulta,Perfil::setListarConsulta);
            mapper.map(PerfilDto::isCadastrarEspecialidade,Perfil::setCadastrarEspecialidade);
            mapper.map(PerfilDto::isLerEspecialidade,Perfil::setLerEspecialidade);
            mapper.map(PerfilDto::isAtualizarEspecialidade,Perfil::setAtualizarEspecialidade);
            mapper.map(PerfilDto::isDeletarEspecialidade,Perfil::setDeletarEspecialidade);
            mapper.map(PerfilDto::isListarEspecialidade,Perfil::setListarEspecialidade);
            mapper.map(PerfilDto::isCadastrarEspecialidade,Perfil::setCadastrarEspecialidade);
            mapper.map(PerfilDto::isLerEspecialidade,Perfil::setLerEspecialidade);
            mapper.map(PerfilDto::isAtualizarEspecialidade,Perfil::setAtualizarEspecialidade);
            mapper.map(PerfilDto::isDeletarEspecialidade,Perfil::setDeletarEspecialidade);
            mapper.map(PerfilDto::isListarEspecialidade,Perfil::setListarEspecialidade);
            mapper.map(PerfilDto::isCadastrarConvenio,Perfil::setCadastrarConvenio);
            mapper.map(PerfilDto::isLerConvenio,Perfil::setLerConvenio);
            mapper.map(PerfilDto::isAtualizarConvenio,Perfil::setAtualizarConvenio);
            mapper.map(PerfilDto::isDeletarConvenio,Perfil::setDeletarConvenio);
            mapper.map(PerfilDto::isListarConvenio,Perfil::setListarConvenio);
            mapper.map(PerfilDto::isCadastrarProntuario,Perfil::setCadastrarProntuario);
            mapper.map(PerfilDto::isLerProntuario,Perfil::setLerProntuario);
            mapper.map(PerfilDto::isAtualizarProntuario,Perfil::setAtualizarProntuario);
            mapper.map(PerfilDto::isDeletarProntuario,Perfil::setDeletarProntuario);
            mapper.map(PerfilDto::isListarProntuario,Perfil::setListarProntuario);
            mapper.map(PerfilDto::isCadastrarPerfil,Perfil::setCadastrarPerfil);
            mapper.map(PerfilDto::isLerPerfil,Perfil::setLerPerfil);
            mapper.map(PerfilDto::isAtualizarPerfil,Perfil::setAtualizarPerfil);
            mapper.map(PerfilDto::isDeletarPerfil,Perfil::setDeletarPerfil);
            mapper.map(PerfilDto::isListarPerfil,Perfil::setListarPerfil);
        });
        modelMapper.typeMap(Perfil.class,PerfilDto.class).addMappings(mapper -> {
            mapper.map(Perfil::isCadastrarFuncionario, PerfilDto::setCadastrarFuncionario);
            mapper.map(Perfil::isLerFuncionario,PerfilDto::setLerFuncionario);
            mapper.map(Perfil::isAtualizarFuncionario,PerfilDto::setAtualizarFuncionario);
            mapper.map(Perfil::isDeletarFuncionario,PerfilDto::setDeletarFuncionario);
            mapper.map(Perfil::isListarFuncionario,PerfilDto::setListarFuncionario);
            mapper.map(Perfil::isCadastrarPaciente,PerfilDto::setCadastrarPaciente);
            mapper.map(Perfil::isLerPaciente,PerfilDto::setLerPaciente);
            mapper.map(Perfil::isAtualizarPaciente,PerfilDto::setAtualizarPaciente);
            mapper.map(Perfil::isDeletarPaciente,PerfilDto::setDeletarPaciente);
            mapper.map(Perfil::isListarPaciente,PerfilDto::setListarPaciente);
            mapper.map(Perfil::isCadastrarConsulta,PerfilDto::setCadastrarConsulta);
            mapper.map(Perfil::isLerConsulta,PerfilDto::setLerConsulta);
            mapper.map(Perfil::isAtualizarConsulta,PerfilDto::setAtualizarConsulta);
            mapper.map(Perfil::isDeletarConsulta,PerfilDto::setDeletarConsulta);
            mapper.map(Perfil::isListarConsulta,PerfilDto::setListarConsulta);
            mapper.map(Perfil::isCadastrarEspecialidade,PerfilDto::setCadastrarEspecialidade);
            mapper.map(Perfil::isLerEspecialidade,PerfilDto::setLerEspecialidade);
            mapper.map(Perfil::isAtualizarEspecialidade,PerfilDto::setAtualizarEspecialidade);
            mapper.map(Perfil::isDeletarEspecialidade,PerfilDto::setDeletarEspecialidade);
            mapper.map(Perfil::isListarEspecialidade,PerfilDto::setListarEspecialidade);
            mapper.map(Perfil::isCadastrarEspecialidade, PerfilDto::setCadastrarEspecialidade);
            mapper.map(Perfil::isLerEspecialidade,PerfilDto::setLerEspecialidade);
            mapper.map(Perfil::isAtualizarEspecialidade,PerfilDto::setAtualizarEspecialidade);
            mapper.map(Perfil::isDeletarEspecialidade,PerfilDto::setDeletarEspecialidade);
            mapper.map(Perfil::isListarEspecialidade,PerfilDto::setListarEspecialidade);
            mapper.map(Perfil::isCadastrarConvenio,PerfilDto::setCadastrarConvenio);
            mapper.map(Perfil::isLerConvenio,PerfilDto::setLerConvenio);
            mapper.map(Perfil::isAtualizarConvenio,PerfilDto::setAtualizarConvenio);
            mapper.map(Perfil::isDeletarConvenio,PerfilDto::setDeletarConvenio);
            mapper.map(Perfil::isListarConvenio,PerfilDto::setListarConvenio);
            mapper.map(Perfil::isCadastrarProntuario,PerfilDto::setCadastrarProntuario);
            mapper.map(Perfil::isLerProntuario,PerfilDto::setLerProntuario);
            mapper.map(Perfil::isAtualizarProntuario,PerfilDto::setAtualizarProntuario);
            mapper.map(Perfil::isDeletarProntuario,PerfilDto::setDeletarProntuario);
            mapper.map(Perfil::isListarProntuario,PerfilDto::setListarProntuario);
            mapper.map(Perfil::isCadastrarPerfil,PerfilDto::setCadastrarPerfil);
            mapper.map(Perfil::isLerPerfil,PerfilDto::setLerPerfil);
            mapper.map(Perfil::isAtualizarPerfil,PerfilDto::setAtualizarPerfil);
            mapper.map(Perfil::isDeletarPerfil,PerfilDto::setDeletarPerfil);
            mapper.map(Perfil::isListarPerfil,PerfilDto::setListarPerfil);
        });
        return modelMapper;
    }
}
